#FROM node:18-alpine AS build
FROM nginx:alpine

#WORKDIR /app

WORKDIR /usr/share/nginx/html

#COPY ../../source/frontend/package*.json ./

#RUN npm install

COPY index.html ./index.html

#RUN npm run build

#FROM nginx:alpine

#COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]