groups:
  - name: docker_alerts
    rules:
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[1m]) > 0.8
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High container CPU usage"
